### ISSUE TITLE
Task integration : task-frontend communication

### ISSUE THREAD

**Issue by mblockelet** [France-ioi/AlgoreaFrontend#176]
# Overview

Integrate tasks (and courses) into the frontend. It requires implementing communication between the frontend and the task, and also implementing the backend calls related to items.

This issue only includes tasks directly tied to communication between the frontend and a task : loading, displaying of a task and current answer management. It doesn't include getting actual data (#177), or other actions around tasks (results or attempt management, etc.).

# Subtasks

- [ ] Basic frontend-task communication, with mock data and test buttons
  - [ ] Make item-task component with iframe
  - [ ] Get dependencies (jschannel, task-xd-pr, ...?)
  - [ ] task load
  - [ ] task views management
  - [ ] task answer/state (load/save, from task into memory)
  - [ ] task unload
- [ ] Design integration
  - [ ] Normal iframe dimensions (iframe height adjusts to the task as is usually done on other platforms)
  - [ ] Responsive mode (iframe stays in the visible window)
  - [ ] Use proper tabs for the views

_This list might not be exhaustive._

**Comment by smadbe** [comment]
completed by Thomas in other issues
