### ISSUE TITLE
Algorea: features to be implemented & priorities

### ISSUE THREAD

**Issue by smadbe** [France-ioi/AlgoreaFrontend#491]
### TODO/Ongoing
- [x] #536
- [x] group permission page (#600 + ...)

### Completed
<details>
  <summary>show/hide</summary>

- [x] Group composition > group code generation. Fix multiple usability issues.  (https://github.com/France-ioi/AlgoreaBackend/issues/768 + #541)
- [x] Fix cross-domain cookies (#531)
- [x] Item edition, children edition. Fix : non visible children get removed at save (https://github.com/France-ioi/AlgoreaBackend/issues/767 + #542)
- [x] Item edition, children edition: allow editing propagation (#529 + https://github.com/France-ioi/AlgoreaBackend/issues/776)
- [x] item edition: allow editing url, use api and text id for courses (#528  )
- [x] #530
- [x] #540
- [x] #576
- [x] #532
- [x] Item edition, children edition: do not loose propagation at save (#516)
- [x] manager list: indicator showing if the manager can watch etc the group (in SNT, it is "X" while it is enabled) (#505)
- [x] can_edit=children not well handled... edition button shown but "not allowed to edit" message afterwards (#506)
- [x] when no children, the spacing between component is not ideal (#494)
- [x] fix item edition which was failing or messing with permission propagation 
</details>

### Task loading
- [x] #782 
- [x] in observation mode, do not load the current answer by default, just launch the empty task in read-only. (#788)
- [x] keep task open when on progress tab (#790)
- [x] load task: when loading an answer from another user (observation mode), load it in readonly + indicate the user + the score and the date of submission  (#816)
- [x] on load: save current state if different from what was loaded/submitted (#813)
- [ ] save current state button (on progress tab?)
- [ ] "fork" a read-only answer

### TODO/Ongoing

- [x] Task integration, first steps (#628)
- [x] export results as csv (https://github.com/France-ioi/AlgoreaBackend/pull/786 #641)
- [x] allow removing a subgroup from a group [2F] (#334)
- [x] item deletion [0.5B+1F]  (#642)
- permission popup:
   - [x] Constraints between permissions #593
   - [x] Limit to permissions which can be granted
   - [x] Display computed permissions
   - [ ] Display group permissions given by other groups.
- [x] Collapsed header: add score (#629 and #630)
- [x] Collapsed header: add prev/next/parent #771 
- [x] prev/next/parent for groups as well #772 
- [x] Basic style improvement for prev/next/parent component: highlight on hover, separator?, less space on left
- [x]  #554
- [x] [add group managers](https://france-ioi.github.io/algorea-designs/01.Groups_03.Administration) (waiting for https://github.com/France-ioi/AlgoreaBackend/issues/801)
- [x] [In observation mode, display the permissions the observed groups has on visited item](https://github.com/France-ioi/algorea-designs/blob/master/img/03.Activities_00.Header_e.Access%20to%20activity%20(point%20of%20view).png) (#750 and #751)
- [ ] Does not display team/user/sessions at multiple places when there is no team/user/sessions in the progress tab
- [ ] Keep the same filters when switching between group on composition pages
- [x] Better handling of item with low permissions (can_view:info): #585, #584, #583
- [x] Keep the same sub-page (log, history) when navigating between items
- [x] Keep the same sub-page  when navigating between groups
- [x] on group page: leave the group (handle locked memberships, team memberships) (design [1](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_n.Leave-the-group) and [2](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_p.Team-members-locked)) #774
- [x] Observation mode: check item permissions
- [x] Observation mode: display observed group scores in UI
- [x] Observation mode: should display on top of the activities/skills that we are in observation mode
- [x] Handle result matrix when there is no children (so no columns) #535 
- [x] fix breadcrumb for user page (progress displayed even if no right to see progress)
- [x] have left menu adapted to observation mode (content + warning)
- [x] Add bug/crash tracking in JS
- [ ] prod DB migration
- [x] pagination
- [ ] #348 
- [ ] #442
- [x] add "retry" button on errors (#639)
- [x] make sure manager groups have a path when navigating to their page for a basic user (does the search path works? does the get group works?)  

### Completed

<details>
  <summary>show/hide</summary>

- [x] #446 
- [x] Various left menu esthetic improvements: #551, #552, #565, #586
- [x] to check: if the progress matrix is empty, we cannot configure any access?
- [x] Group and user progress
- [x] Unify "yourself" and other user's pages
- [x] have the "observe" button on users' page (#553)
- [x] #545
- [x] #546
- [x] Improve/fix progress tab for items: #570, #574, #568, #567
- [x] Deployment infrastructure setup (including #462 )
</details>

## Important refactoring:
Low effort:
- [x] error component + use it everywhere (#634)
- [x] loading component + use it everywhere (#635)
- [x] convert remaining 'loading'|'error' to state (mapToFetchState) (#636)
- [x] convert all services to decoder (#638)
- [ ] mapToFetchState -> split `resetter` in `refetcher` (which keep the former state in data) and `resetter` (which does not)

More complex:
- [x] Current-content
- [x] Permission enums through all the app
- [x] Watching in path
- [x] Get rid of editing

## Other features:
- [ ] batch user creation ([design](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_01.Dialogs_02.Create-batch-accounts))
- [ ] [dialog for joining group](https://france-ioi.github.io/algorea-designs/01.Groups_02.Composition_01.Dialogs_09/Join-a-group)
- [ ] attempt list on item (designs [1](https://france-ioi.github.io/algorea-designs/03.Activities_00.Header_d.Attempt), [2](https://france-ioi.github.io/algorea-designs/03.Activities_00.Header_d.Attempt_a.Open))
- [x] in item children: add key on item unlocking other items (require it [to be added to the backend](https://github.com/France-ioi/AlgoreaBackend/issues/697)) ([design](https://france-ioi.github.io/algorea-designs/03.Activities_01.Content__structure))
- [ ] list official session of an item

## Minor/low-priority bugs and features:
- [ ] handle item children with a same order

**Comment by smadbe** [comment]
They have all been done or copied in another todo list.
